board/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    # url(r'^single/(?P<pk>\d+)/$', views.post_single, name='post_single'),
    url (r'^search/$', views.search, name='search'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from mysite.views import HomeView
from mysite.views import UserRegisterView, UserRegisterDoneView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserRegisterView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserRegisterDoneView.as_view(), name='register_done'),
    url(r'^board/', include('board.urls', namespace='board')),
]

board/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django import forms

def min_length_3_validator(value):
	if len(value) < 3:
		raise forms.ValidationError('3글자 이상 입력해주세요')


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200, validators=[min_length_3_validator])
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    modified_date = models.DateTimeField(
            blank=True, null=True)

    def get_absolute_url(self): # redirect시 활용
        return reverse('board:post_detail', args=[self.id])

    def __str__(self):
        return self.title

# class Comment(models.Model):
#     post = models.ForeignKey('board.Post', related_name='comments')
#     author = models.CharField(max_length=200)
#     text = models.TextField()
#     created_date = models.DateTimeField(default=timezone.now)
#     approved_comment = models.BooleanField(default=False)

#     def approve(self):
#         self.approved_comment = True;
#         self.save()
    
#     def __str__(self):
#         return self.text

board/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)


class BoardSearchForm(forms.Form):
    search_word = forms.CharField(label='검색')

board/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.utils import timezone
from .models import Post
from .forms import PostForm, BoardSearchForm
from django.db.models import ProtectedError
from django.views.generic.edit import FormView
from .forms import BoardSearchForm

# Create your views here.
def post_list(request):
    posts = Post.objects.all()
    form = BoardSearchForm()
    return render(request, 'board/post_list.html', {'posts': posts, 'form':form})

def post_detail(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     return render(request, 'board/post_detail.html', { 'post':post })
#
# def post_single(request, pk):
    posts = Post.objects.filter(pk__gt=pk)
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'board/post_single.html', { 'post':post, 'posts': posts })

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.modified_date = timezone.now()
            post.save()
            return redirect('board:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'board/post_edit.html', {'form':form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.modified_date = timezone.now()
            post.save()
            return redirect('board:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'board/post_edit.html', {'form':form})

def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author == request.user:
        post.delete()
        return redirect('board:post_list')


def search(request):
    # if request.method == 'GET':
    #     form = BoardSearchForm(request.GET)
    #     if 'search_word' in request.GET:
    #         results = Post.objects.filter(text__contains = request.GET['search_word'])
    #     return render(request, 'board/post_search.html', {'results': results})
    # else:
    #     form = BoardSearchForm()
    # return render(request, 'board/post_search.html',{'form':form} )
    if 'search_word' in request.GET and request.GET['search_word']:
        sWord = request.GET['search_word']
        results = Post.objects.filter(text__icontains = sWord)
        return render(request, 'board/post_search.html', {'results': results, 'query': sWord})
    else:
        return HttpResponse('검색어를 입력 해 주세요.')

mysite/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy

class HomeView(TemplateView):
    template_name = 'home.html'

class UserRegisterView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserRegisterDoneView(TemplateView):
    template_name = 'registration/register_done.html'

board/templates/board/base_board.html
{% extends "base.html" %}
{% block title %}
| 식품상점
{% endblock title %}
{% block content %}
    <title>myboard</title>
    <h1><a href="{% url 'board:post_list' %}">myboard</a></h1>
    {% if user.is_authenticated %}
    <div><a href="{% url 'board:post_new' %}">쓰기</a></div>
    {% endif %}
    {% block board_content %}
    {% endblock %}
{% endblock content %}

board/templates/board/post_detail.html
{% extends 'board/base_board.html' %}
{% block board_content %}
{% if user.is_authenticated %}
<div><a href="{% url 'board:post_edit' pk=post.pk %}">수정</a></div>
{% endif %}
<div class="panel panel-default">
    <div class="panel-heading">{{ post.title }}</div>
    <div class="panel-body">{{ post.text|linebreaksbr}}</div>
</div>
{% endblock %}

board/templates/board/post_edit.html
{% extends 'board/base_board.html' %}
{% block board_content %}
<h2>New post</h2>
<form method="POST" class="post-form">{% csrf_token %}
        <div class="form-group">
                <div class="form-group">{{ form.username.label_tag }}{{ form.title }}</div>
                <div class="form-group">{{ form.username.label_tag }}{{ form.text }}</div>

<button type="submit"  class="btn btn-default">저장</button>
</div>
</form>
<script>
        (function () {
            document.querySelector("input[name='title']").classList.add('form-control');
            // input type="text" name="title"
            document.querySelector("textarea[name='text']").classList.add('form-control');
        })();
    </script>
{% endblock %}

board/templates/board/post_list.html
{% extends 'board/base_board.html' %}
{% block board_content %}
<!-- table-bordered, table-hover, table-condensed -->
<!-- tr태그에 active, success, info, warning, danger  -->
<!-- <div class="table-responsive"> -->
<div class="table-responsive">
    <table class="table">
    <tr>
        <td>순번</td>
        <td>제목</td>
        <td>작성자</td>
        <td>작성일</td>
    </tr>
{% for post in posts %}
    <tr>
        <td>{{ post.id }}</td>
        <td><a href="{% url 'board:post_detail' pk=post.pk %}">{{ post.title }}</a>
            {% if post.author.id == user.id %}
            <a href="{% url 'board:post_remove' pk=post.pk %}">[del]</a>
            {% endif %}
        </td>
        <td>{{ post.author }}</td>
        <td>{{ post.created_date|date:"M/d"|lower }}</td>
    </tr>
{% endfor %}
</table>
</div>
<form method="GET" class="post-form" action="{% url 'board:search' %}">
    <div class="form-group">
        <div class="form-group">{{form.search_word.label}}{{ form.search_word }}</div>
        <button type="submit"  class="btn btn-default">검색</button>
    </div>
</form>
{% endblock %}

board/templates/board/post_search.html
{% extends 'board/base_board.html' %}
{% block board_content %}
<form method="POST" class="post-form">{% csrf_token %}
    <div class="form-group">
        <div class="form-group">{{ form.search_word }}</div>
        <button type="submit"  class="btn btn-default">검색</button>
    </div>
</form>
{% if results %}
{% for post in results %}
    <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
{% endfor %}

{% elif search_term %}
<b><i>Search Word Not Found !</i></b>
{% endif %}

{% endblock %}

board/templates/board/post_single.html
{% extends 'board/base_board.html' %}
{% block board_content %}
{% if user.is_authenticated %}
<div><a href="{% url 'board:post_edit' pk=post.pk %}">수정</a></div>
{% endif %}
<div class="panel panel-default">
    <div class="panel-heading">{{ post.title }}</div>
    <div class="panel-body">{{ post.text|linebreaksbr}}</div>
</div>
<div class="table-responsive">
    <table class="table">
        {% for post in posts %}
        <tr>
            <td>{{ post.id }}</td>
            <td><a href="{% url 'board:post_detail' pk=post.pk %}">{{ post.title }}</a>
                {% if post.author.id == user.id %}
                <a href="{% url 'board:post_remove' pk=post.pk %}">[del]</a>
                {% endif %}
            </td>
            <td>{{ post.author }}</td>
            <td>{{ post.created_date|date:"M/d"|lower }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>장고 게시판{% block title %}{% endblock title %}</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  {% load staticfiles %}
  <!--link rel="stylesheet" href="{% static " css/base.css " %}"-->{% block sub_style %}{% endblock %}
</head>

<body>
  <nav class="nav">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="{% url 'home' %}" class="navbar-brand">Dj Board 2017</a>
      </div>
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'home' %}">홈</a>
        </li>
        <li>
          <a href="{% url 'board:post_list' %}">게시판</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_active %}
        <li>
          <a>{% firstof user.get_short_name user.get_username %}님 입장</a>
        </li>
        <li>
          <a href="{% url 'password_change' %}">비밀번호 변경</a>
        </li>
        {% if user.is_superuser %}
        <li>
          <a href="{% url 'admin:index' %}">관리자</a>
        </li>
        {% endif %}
        <li>
          <a href="{% url 'logout' %}">로그아웃</a>
        </li>
        {% else %}
        <li>
          <a>환영합니다.</a>
        </li>
        <li>
          <a href="{% url 'login' %}">로그인</a>
        </li>
        <li>
          <a href="{% url 'register' %}">회원가입</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock %}
    <!-- {% block footer %}
    {% endblock %} -->
    <footer>&copy; 2017. (이름) All right reserved.</footer>
  </div>
</body>

</html>

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block sub_style %}
<!-- <link rel="stylesheet" href="{% static 'css/home_style.css' %}"> -->
{% endblock %}
{% block title %}
 | 환영합니다.
{% endblock title %}
{% block content %}
        <div class="jumbotron">
        <h1>환영합니다.</h1>
        <p>군영과 우리 인생을 이상의 보내는 얼마나 설레는 실현에 있다. 용기가 지혜는 못하다 있다.</p>
        <p>사라지지 청춘이 못할 봄바람을 어디 위하여 때문이다. 얼마나 뜨고, 이것을 인도하겠다는 그들의 사랑의 이상의 때문이다. 불러 따뜻한 인간의 인도하겠다는 우리 있다.</p>
      </div>
      <p>가치를 열락의 지혜는 우는 청춘 사랑의 예가 주는 것이다. 불러 스며들어 그들에게 일월과 하여도 천지는 목숨을 실현에 부패뿐이다.</p>
{% endblock content %}